name: x11 CI testground
on: [push, pull_request]
jobs:
  build:
    name: Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Install
        id: install
        run: |
          sudo apt-get update
          sudo apt-get full-upgrade -y
          sudo apt-get autoremove -y
          sudo apt-get install -y xorg openbox mesa-utils
